name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: art
    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run tests and save output
        run: |
          mkdir -p test-results
          npm run check > test-results/output.txt || true

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/output.txt

  deploy:
    runs-on: art
    needs: test
    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Download test result artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./downloaded-test-results

      - name: Show test result
        run: cat ./downloaded-test-results/output.txt

      - name: install pm2
        run: npm i -g pm2

      - name: remove existing pm2 instance
        run: pm2 delete node-app || true

      - name: Deploy
        run: pm2 start "./src/server.js" --name node-app

      - name: Success message
        run: echo deployed
